[package]
name = "dua-cli"
version = "2.8.2"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
edition = "2018"
repository = "https://github.com/Byron/dua-cli"
readme = "README.md"
description = "A tool to conveniently learn about the disk usage of directories, fast!"
license = "MIT"
include = ["src/**/*", "Cargo.*", "LICENSE", "README.md", "CHANGELOG.md", "!**/*_test/*"]

[dependencies]
structopt = "0.3.15"
jwalk = "0.5.0"
byte-unit = "4"
termion = "1.5.2"
atty = "0.2.11"
tui = "0.9.1"
petgraph = "0.5"
itertools = "0.9.0"
open = "1.2.2"
log = "0.4.6"
tui-react = { version = "0.4" }
num_cpus = "1.10.0"
unicode-segmentation = "1.3.0"
filesize = "0.2.0"
flume = {version = "0.7.1", default-features = false}
anyhow = "1.0.31"

[target.'cfg(windows)'.dependencies]
crosstermion = { version = "0.1.3", default-features = false, features = ["tui-react-crossterm", "input-thread-flume"]}

[target.'cfg(unix)'.dependencies]
crosstermion = { version = "0.1.3", default-features = false, features = ["tui-react-termion", "input-thread-flume"]}

[[bin]]
name="dua"
path="src/main.rs"

[lib]
name="dua"

[profile.release]
panic = 'abort'
incremental = false
overflow-checks = false
lto = "fat"
codegen-units = 1

[dev-dependencies]
# Tests only run on linux as we use some conveniences offered by termion
termion = "1.5.2"
pretty_assertions = "0.6.1"

[workspace]
members = ["tui-react"]
