name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: make unit-tests
    - name: fmt
      run: cargo fmt --all -- --check
    - name: clippy
      run: cargo clippy
    - name: Check crate package size (feat. 'cargo diet')
      run: |
        curl -LSfs https://raw.githubusercontent.com/the-lean-crate/cargo-diet/master/ci/install.sh | \
         sh -s -- --git the-lean-crate/cargo-diet --target x86_64-unknown-linux-musl

        cargo diet -n --package-size-limit 30KB

